# Generated by Django 4.0.6 on 2022-07-20 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readcsv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('transaction_id', models.UUIDField(primary_key=True, serialize=False)),
                ('transaction_time', models.DateTimeField(auto_now_add=True)),
                ('product_name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.FloatField()),
                ('total_price', models.FloatField()),
                ('delivered_to_city', models.CharField(max_length=255)),
            ],
        ),
    ]
