# Generated by Django 4.0.6 on 2022-07-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readcsv', '0002_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='transaction_id',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='file',
            name='transaction_time',
            field=models.DateTimeField(),
        ),
    ]
