# Generated by Django 4.0.6 on 2022-07-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readcsv', '0003_file_id_alter_file_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
